---
# Source: karpenter/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: karpenter
  namespace: kube-system
  labels:
    application: kubernetes
    component: karpenter
  annotations:
{{- if eq .Cluster.Provider "zalando-eks"}}
    eks.amazonaws.com/role-arn: "arn:aws:iam::{{.Cluster.InfrastructureAccountID}}:role/{{ .Cluster.LocalID }}-app-karpenter"
{{- else}}
    iam.amazonaws.com/role: '{{ .Cluster.LocalID }}-app-karpenter'
{{- end}}
automountServiceAccountToken: false
