---
# Source: karpenter/templates/secret-webhook-cert.yaml
apiVersion: v1
kind: Secret
metadata:
  name: karpenter-cert
  namespace: kube-system
  labels:
    application: kubernetes
    component: karpenter
# data: {} # Injected by karpenter-webhook
