apiVersion: batch/v1
kind: CronJob
metadata:
  name: karpenter-v1-migrator
  namespace: "kube-system"
  labels:
    application: kubernetes
    component: karpenter-v1-migrator
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 300
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      activeDeadlineSeconds: 300
      backoffLimit: 0
      template:
        metadata:
          labels:
            application: kubernetes
            component: karpenter-v1-migrator
          annotations:
            logging/destination: "{{.Cluster.ConfigItems.log_destination_infra}}"
        spec:
          serviceAccountName: karpenter
          restartPolicy: Never
          containers:
          - name: karpenter-v1-migrator
            image: container-registry.zalando.net/teapot/karpenter-v1-migrator:main-2
            args:
            - -mode=nc-fix
            resources:
              limits:
                cpu: 100m
                memory: 100Mi
              requests:
                cpu: 100m
                memory: 100Mi
