# {{ if eq .Cluster.ConfigItems.skipper_ingress_operator_enabled "true" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skipper-ingress-operator
  namespace: kube-system
  labels:
    application: skipper-ingress
    component: operator
spec:
  replicas: 1
  selector:
    matchLabels:
      application: skipper-ingress
      component: operator
  template:
    metadata:
      labels:
        application: skipper-ingress
        component: operator
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "9911"
        prometheus.io/scrape: "true"
        kubernetes-log-watcher/scalyr-parser: |
          [{"container": "skipper-ingress-operator", "parser": "keyValue"}]
        logging/destination: "{{ .Cluster.ConfigItems.log_destination_both }}"
    spec:
      serviceAccountName: skipper-ingress-operator
      containers:
      - name: skipper-ingress-operator
        terminationMessagePolicy: FallbackToLogsOnError
        image: container-registry.zalando.net/gwproxy/skipper-ingress-operator:main-44
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        args:
          - "--dry-mode=true"
          - "--prometheus-url=http://prometheus.kube-system.svc.cluster.local"
          - "--log-level=debug"
          - "--use-mem-query"
          - "--use-status-query"
          - "--metrics-addr=:9911"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
# {{ end }}
