{{ if eq .Cluster.Environment "e2e" }}
{{ range $pool := split "worker-limit-az,worker-instance-storage,worker-node-tests,worker-arm64" "," }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pool-reserve-{{$pool}}
  labels:
    application: pool-reserve
spec:
  replicas: 1
  selector:
    matchLabels:
      application: pool-reserve
      pool: "{{$pool}}"
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        application: pool-reserve
        pool: "{{$pool}}"
    spec:
      {{- if eq $pool "worker-arm64" }}
      nodeSelector:
        kubernetes.io/arch: arm64
      {{- else if ne $pool "worker-instance-storage" }}
      nodeSelector:
        node.kubernetes.io/node-pool: "{{$pool}}"
      {{- end }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: pool
                operator: In
                values:
                - "{{$pool}}"
            topologyKey: "kubernetes.io/hostname"
      tolerations:
      {{ if eq $pool "worker-node-tests" }}
        - effect: NoSchedule
          key: dedicated
          value: node-tests
      {{ end }}
      terminationGracePeriodSeconds: 0
      containers:
      - name: pause
        image: container-registry.zalando.net/teapot/pause:3.9-master-23
        resources:
          limits:
            cpu: 1m
            memory: 50Mi
          requests:
            cpu: 1m
            memory: 50Mi
            {{- if eq $pool "worker-instance-storage" }}
            ephemeral-storage: "500Gi"
            {{- end }}
---
{{ end }}
{{ end }}
