apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    application: polarsignals
    component: agent
  name: polarsignals-conf
  namespace: polarsignals
data:
  parca-agent.yml: |-
    relabel_configs:
    - source_labels: [comm]
      regex: skipper(.*)
      action: keep
