{{ if eq .Cluster.ConfigItems.polarsignals_enabled "true" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: polarsignals-agent
  namespace: polarsignals
  labels:
    component: agent
    application: polarsignals
stringData:
  token: {{ .Cluster.ConfigItems.polarsignals_apikey }}
{{ end }}
