{{ if eq .Cluster.ConfigItems.polarsignals_enabled "true" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: polarsignals-agent
  namespace: polarsignals
  labels:
    app.kubernetes.io/component: continuous-profiler
    app.kubernetes.io/instance: polarsignals-agent
    app.kubernetes.io/name: polarsignals-agent
stringData:
  token: {{ .Cluster.ConfigItems.polarsignals_apikey }}
{{ end }}
