{{- if eq .Cluster.ConfigItems.s3_csi_driver "true" }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: mount-s3
  labels:
    name: mount-s3
    application: kubernetes
    component: aws-mountpoint-s3-csi-driver
    pod-security.kubernetes.io/enforce: restricted
{{- end }}
