apiVersion: v1
kind: ConfigMap
metadata:
  name: spiffe-helper
  namespace: spire
data:
  helper.conf: |
    cmd = ""
    cmd_args = ""
    agent_address = "/tmp/spire-agent/public/agent.sock"
    cert_dir = "/data"
    renew_signal = ""
    svid_file_name = "tls.crt"
    svid_key_file_name = "tls.key"
    svid_bundle_file_name = "ca.pem"
    jwt_bundle_file_name = "cert.jwt"
    jwt_svids = [{jwt_audience="test", jwt_svid_file_name="jwt_svid.token"}]
    daemon_mode = false
    #add_intermediates_to_bundle = true
