apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterSPIFFEID
metadata:
  name: spiff-helper
  namespace: spire
spec:
  spiffeIDTemplate: "spiffe://pg9-euc1-test.test.k8s.zalando.com/spiffe-helper/cmp/api"
  #spiffeIDTemplate: "spiffe://apps.pg9-euc1-test.test.k8s.zalando.com/{{ index .PodMeta.Labels \"application\" }}/cmp/{{ index .PodMeta.Labels \"component\" }}"
  #spiffeIDTemplate: "spiffe://apps.{{ .Cluster.Alias }}.test.k8s.zalando.com/\{\{ index .PodMeta.Labels \"application\" \}\}/cmp/\{\{ index .PodMeta.Labels \"component\" \}\}"
  podSelector:
    matchExpressions:
      - key: application
        operator: Exists
      - key: component
        operator: Exists
    # optional: restrict my test application
    # matchLabels:
    #   application: spiffe-helper
    #   component: api
  # optional: namespace restriction
  # namespaceSelector:
  #   matchLabels:
  #     spire-enabled: "true"
