{{ if eq .Cluster.ConfigItems.wiz_enable_runtime_monitoring_daemonset "true"}}
---
# Source: wiz-kubernetes-integration/charts/wiz-kubernetes-connector/templates/service-account-modify-connector.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: wiz-auto-modify-connector
  namespace: "wiz"
  labels:
    helm.sh/chart: wiz-kubernetes-connector-3.1.1
    app.kubernetes.io/name: wiz-kubernetes-connector
    app.kubernetes.io/instance: wiz-connector
    app.kubernetes.io/version: "2.5"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,pre-delete
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "-1"
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["wiz-connector-connector"]
    verbs: ["update", "get"]
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: [
      "wiz-api-token",
      "wiz-cluster-reader-token",
    ]
    verbs: ["get"]
---
# Source: wiz-kubernetes-integration/charts/wiz-kubernetes-connector/templates/service-account-modify-connector.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wiz-auto-modify-connector
  namespace: "wiz"
  labels:
    helm.sh/chart: wiz-kubernetes-connector-3.1.1
    app.kubernetes.io/name: wiz-kubernetes-connector
    app.kubernetes.io/instance: wiz-connector
    app.kubernetes.io/version: "2.5"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,pre-delete
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "-1"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name:  wiz-auto-modify-connector
subjects:
- kind: ServiceAccount
  name: wiz-auto-modify-connector
  namespace: "wiz"
{{end}}
