{{ if eq .Cluster.ConfigItems.wiz_enable_runtime_monitoring_daemonset "true"}}
---
# Source: wiz-kubernetes-integration/charts/wiz-kubernetes-connector/templates/secret-connector.yaml
apiVersion: v1
kind: Secret
metadata:
  name: wiz-connector-connector
  namespace: "wiz"
  labels:
    helm.sh/chart: wiz-broker-2.1.0
    application: "wiz"
    component: "connector"
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "-1"
type: Opaque
data:
  connectorData: "e30="
---
# Source: wiz-kubernetes-integration/charts/wiz-kubernetes-connector/templates/service-account-cluster-reader.yaml
apiVersion: v1
kind: Secret
metadata:
  name: wiz-cluster-reader-token
  namespace: "wiz"
  labels:
    helm.sh/chart: wiz-broker-2.1.0
    application: "wiz"
    component: "connector"
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    kubernetes.io/service-account.name: wiz-cluster-reader
type: kubernetes.io/service-account-token
---
# Source: wiz-sensor/templates/apikeysecret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: wiz-api-token
  namespace: wiz
  labels:
    
    helm.sh/chart: wiz-broker-2.1.0
    application: "wiz"
    component: "connector"
type: Opaque
data:
  clientId: "{{ .Cluster.ConfigItems.wiz_api_client_id | base64 }}"
  clientToken: "{{ .Cluster.ConfigItems.wiz_api_client_token | base64 }}"
{{end}}
