# {{- if and (eq .Cluster.Provider "zalando-eks") (eq .Cluster.ConfigItems.eks_efs_csi_support_enabled "true") }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: "{{ .Values.ClusterStackOutputs.EFSFileSystemID }}"
  directoryPerms: "700"
# {{- end }}
