apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-monitor
  namespace: kube-system
  labels:
    application: kubernetes
    component: node-monitor
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      daemonset: node-monitor
  template:
    metadata:
      labels:
        daemonset: node-monitor
        application: kubernetes
        component: node-monitor
      annotations:
        logging/destination: "{{.Cluster.ConfigItems.log_destination_infra}}"
    spec:
      hostNetwork: true
      hostPID: true
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      priorityClassName: system-node-critical
      serviceAccountName: node-monitor
      containers:
        - image: container-registry.zalando.net/teapot/prometheus-node-exporter:v1.9.1-master-24
          args:
{{- if eq .Cluster.ConfigItems.node_exporter_experimental_metrics "true" }}
            - --collector.ethtool
{{- end }}
            - --collector.processes
            - --path.procfs=/host/proc
            - --path.sysfs=/host/sys
            - --path.rootfs=/host
            - --no-collector.wifi
            - --no-collector.hwmon
            - --no-collector.btrfs
            - --collector.filesystem.mount-points-exclude=^/(dev|proc|run|sys|host|var/lib/lxcfs|opt/podruntime/containerd/.+|opt/podruntime/kubelet/.+)($|/)
            - --collector.netdev.device-exclude=^veth.*$
            - --collector.netclass.ignored-devices=^veth.*$
          name: prometheus-node-exporter
          ports:
            - name: prom-node-exp
              containerPort: 9100
              hostPort: 9100
              protocol: TCP
          resources:
            requests:
              cpu: {{.Cluster.ConfigItems.node_exporter_cpu}}
              memory: {{.Cluster.ConfigItems.node_exporter_memory}}
              ephemeral-storage: 256Mi
            limits:
              cpu: {{.Cluster.ConfigItems.node_exporter_cpu}}
              memory: {{.Cluster.ConfigItems.node_exporter_memory}}
          securityContext:
            privileged: true
          volumeMounts:
            - name: rootfs
              mountPath: /host
              readOnly: true
{{- if eq .Cluster.ConfigItems.journald_reader_enabled "true" }}
        - image: container-registry.zalando.net/teapot/journald-reader:master-19
          name: journald-reader
          env:
            - name: JOURNALD_READER_CHECKPOINT_FILE
              value: /journald-reader-state/cursor
          resources:
            requests:
              cpu: {{.Cluster.ConfigItems.journald_reader_cpu}}
              memory: {{.Cluster.ConfigItems.journald_reader_memory}}
              ephemeral-storage: 256Mi
            limits:
              cpu: {{.Cluster.ConfigItems.journald_reader_cpu}}
              memory: {{.Cluster.ConfigItems.journald_reader_memory}}
          volumeMounts:
            - mountPath: /var/log/journal
              name: journald-logs
              readOnly: true
            - mountPath: /journald-reader-state
              name: journald-reader-state
            - mountPath: /usr
              name: usr
              readOnly: true
{{- end }}
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: 30
      volumes:
        - name: rootfs
          hostPath:
            path: /
        - name: var-run
          hostPath:
            path: /var/run
        - name: sys
          hostPath:
            path: /sys
        - name: usr
          hostPath:
            path: /usr
        - name: containerd
          hostPath:
            path: /opt/podruntime/containerd
        - name: kmsg
          hostPath:
            path: /dev/kmsg
{{- if eq .Cluster.ConfigItems.journald_reader_enabled "true" }}
        - name: journald-logs
          hostPath:
            path: /var/log/journal
        - name: journald-reader-state
          hostPath:
            path: /var/run/journald-reader
            type: DirectoryOrCreate
{{- end }}
      tolerations:
        - operator: Exists
          effect: NoSchedule
        - operator: Exists
          effect: NoExecute
