{{ if eq .Cluster.ConfigItems.aws_efa_device_plugin_enabled "true" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-efa-k8s-device-plugin
  namespace: kube-system
  labels:
    application: kubernetes
    component: aws-efa-k8s-device-plugin
{{ end }}
