apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterSPIFFEID
metadata:
  name: dynamic-registration-applications
  namespace: spire
spec:
  spiffeIDTemplate: "spiffe://pg9-euc1-test.test.k8s.zalando.com/app/{{ index .PodMeta.Labels \"application\" }}/cmp/{{ index .PodMeta.Labels \"component\" }}"
  #spiffeIDTemplate: "spiffe://{{ .Cluster.Alias }}.{{ .Cluster.Environment }}.k8s.zalando.com/app/\{\{ index .PodMeta.Labels \"application\" \}\}/cmp/\{\{ index .PodMeta.Labels \"component\" \}\}"
  podSelector:
    matchExpressions:
      - key: application
        operator: Exists
      - key: component
        operator: Exists
    # optional: restrict my test application
    # matchLabels:
    #   application: spiffe-helper
    #   component: api
  # namespace restriction by label
  namespaceSelector:
    matchLabels:
      spire-enabled: "true"
