---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    downscaler/exclude: "true"
  name: spire-server
  namespace: spire
  labels:
    application: spire-server
    component: server
spec:
  replicas: 3
  selector:
    matchLabels:
      application: spire-server
      component: server
  template:
    metadata:
      namespace: spire
      labels:
        application: spire-server
        component: server
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          minDomains: 3
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              application: spire-server
              component: server
      affinity:
       podAntiAffinity:
         requiredDuringSchedulingIgnoredDuringExecution:
         - labelSelector:
             matchExpressions:
             - key: application
               operator: In
               values:
               - spire-server
             - key: component
               operator: In
               values:
               - server
           topologyKey: kubernetes.io/hostname
      priorityClassName: cluster-critical-nonpreempting
      # priorityClassName: "{{ .Cluster.ConfigItems.system_priority_class }}"
      serviceAccountName: spire-server
      shareProcessNamespace: true
      containers:
        - name: spire-server
          image: ghcr.io/spiffe/spire-server:1.15.3
          args:
            - -config
            - /run/spire/server/config/server.conf
          ports:
            - containerPort: 8081
          resources:
            limits:
              memory: 100Mi
              cpu: 100m
            requests:
              memory: 100Mi
              cpu: 100m
          volumeMounts:
            - name: spire-config
              mountPath: /run/spire/server/config
              readOnly: true
            - name: spire-server-socket
              mountPath: /tmp/spire-server/private
        - name: spire-controller-manager
          image: ghcr.io/spiffe/spire-controller-manager:0.7.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9443
            - containerPort: 8083
              name: healthz
          readinessProbe:
            httpGet:
              path: /readyz
              port: healthz
          args:
          - "--config=/spire-controller-manager-config/server.conf"
          resources:
            limits:
              memory: 256Mi
              cpu: 100m
            requests:
              memory: 256Mi
              cpu: 100m
          volumeMounts:
            - name: spire-server-socket
              mountPath: /spire-server
              readOnly: true
            - name: spire-controller-manager-config
              mountPath: /spire-controller-manager-config
      volumes:
        - name: spire-config
          configMap:
            name: spire-server
        - name: spire-server-socket
          emptyDir: {}
        - name: spire-controller-manager-config
          configMap:
            name: spire-controller-manager-config

---

# Service definition for SPIRE server defining the gRPC port.
apiVersion: v1
kind: Service
metadata:
  name: spire-server
  namespace: spire
spec:
  type: NodePort
  ports:
    - name: api
      port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    application: spire-server
    component: server

---

# Service definition for SPIRE server bundle endpoint
apiVersion: v1
kind: Service
metadata:
  name: spire-server-bundle-endpoint
  namespace: spire
spec:
  type: NodePort
  ports:
    - name: api
      port: 8443
      protocol: TCP
  selector:
    application: spire-server
    component: server


---
#
# Service definition for SPIRE controller manager webhook
apiVersion: v1
kind: Service
metadata:
  name: spire-controller-manager-webhook-service
  namespace: spire
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    application: spire-server
    component: server
