{{ if or 
(eq .Cluster.ConfigItems.wiz_enable_runtime_connector "true")
(eq .Cluster.ConfigItems.wiz_enable_runtime_connector_broker "true")
(eq .Cluster.ConfigItems.wiz_enable_runtime_sensor "true")
}}
---
apiVersion: v1
kind: Namespace
metadata:
  name: wiz
{{ end }}
