{{ if eq .Cluster.ConfigItems.wiz_enable_runtime_connector "true"}}
# It is created when wiz_enable_runtime_connector is true and deleted when wiz_enable_runtime_connector_broker  and wiz_enable_runtime_connector is false
---
# Source: wiz-kubernetes-integration/charts/wiz-kubernetes-connector/charts/wiz-broker/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wiz-broker
  namespace: "wiz"
  labels:
    helm.sh/chart: wiz-broker-2.1.0
    application: "wiz"
    component: "connector"
---
# Source: wiz-kubernetes-integration/charts/wiz-kubernetes-connector/templates/service-account-cluster-reader.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wiz-cluster-reader
  namespace: "wiz"
  labels:
    helm.sh/chart: wiz-broker-2.1.0
    application: "wiz"
    component: "connector"
{{end}}
