{{ if eq .Cluster.ConfigItems.wiz_enable_runtime_sensor "true"}}
---
# Source: wiz-kubernetes-integration/charts/wiz-sensor/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wiz-sensor
  labels:
    helm.sh/chart: wiz-sensor-1.0.10341
    application: "wiz"
    component: "sensor"
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]

  - apiGroups: ["", "apps", "batch"]
    resources: [
      "namespaces", "nodes", "daemonsets", "replicasets", "deployments",
      "jobs", "cronjobs", "statefulsets", "replicationcontrollers", "serviceaccounts"
    ]
    verbs: ["get", "list", "watch"]
---
# Source: wiz-kubernetes-integration/charts/wiz-kubernetes-connector/templates/service-account-cluster-reader.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wiz-sensor
  labels:
    helm.sh/chart: wiz-sensor-1.0.10341
    application: "wiz"
    component: "sensor"
subjects:
- kind: ServiceAccount
  name: wiz-sensor
  namespace: wiz
roleRef:
  kind: ClusterRole
  name: wiz-sensor
  apiGroup: rbac.authorization.k8s.io
{{end}}
