{{ if eq .Cluster.ConfigItems.wiz_enable_runtime_connector "true" }}
---
# These are used both in Job and Deployment
# Create when wiz_enable_runtime_connector or wiz_enable_runtime_connector_broker is true and deleted when wiz_enable_runtime_connector_broker and wiz_enable_runtime_connector is false
# Source: wiz-kubernetes-integration/charts/wiz-kubernetes-connector/templates/secret-connector.yaml
apiVersion: v1
kind: Secret
metadata:
  name: wiz-connector-connector
  namespace: "wiz"
  labels:
    helm.sh/chart: wiz-broker-2.3.8
    application: "wiz"
    component: "connector"
type: Opaque
data:
  connectorData: "e30="
{{end}}
{{ if or (eq .Cluster.ConfigItems.wiz_enable_runtime_connector "true") (eq .Cluster.ConfigItems.wiz_enable_runtime_connector_broker "true") }}
---
# Source: wiz-kubernetes-integration/charts/wiz-kubernetes-connector/templates/service-account-cluster-reader.yaml
apiVersion: v1
kind: Secret
metadata:
  name: wiz-cluster-reader-token
  namespace: "wiz"
  labels:
    helm.sh/chart: wiz-broker-2.3.8
    application: "wiz"
    component: "connector"
  annotations:
    kubernetes.io/service-account.name: wiz-cluster-reader
type: kubernetes.io/service-account-token
---
# Source: wiz-sensor/templates/apikeysecret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: wiz-api-token
  namespace: wiz
  labels:
    helm.sh/chart: wiz-broker-2.3.8
    application: "wiz"
    component: "connector"
type: Opaque
stringData:
  clientId: "{{ .Cluster.ConfigItems.wiz_api_client_id }}"
  clientToken: "{{ .Cluster.ConfigItems.wiz_api_client_token }}"
{{end}}
