{{ if eq .Cluster.ConfigItems.wiz_enable_runtime_connector_broker "true"}}
---
# Source: wiz-kubernetes-integration/charts/wiz-kubernetes-connector/charts/wiz-broker/templates/wiz-broker-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiz-connector-agent
  namespace: "wiz"
  labels:
    helm.sh/chart: wiz-broker-3.0.3
    application: "wiz"
    component: "connector"
    deployment: "wiz-connector-agent"
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: "wiz-connector-agent"
  template:
    metadata:
      labels:
        helm.sh/chart: wiz-broker-3.0.3
        application: "wiz"
        component: "connector"
        deployment: "wiz-connector-agent"
    spec:
      serviceAccountName: wiz-broker
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      volumes:
        - name: api-client
          secret:
            secretName: wiz-api-token
        - name: connector-data
          secret:
            secretName: wiz-connector-connector
            items:
              - key: connectorData
                path: data
      containers:
        - name: wiz-broker
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsGroup: 10000
            runAsNonRoot: true
            runAsUser: 10000
          image: "container-registry.zalando.net/secops-systems/wiz-broker:3.0.3-main-8"
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: api-client
            mountPath: /var/api-client
            readOnly: true
          - name: connector-data
            mountPath: /etc/connectorData
            readOnly: true
          args:
            - --connector-data-file-path
            - "/etc/connectorData/data"
          env:
          - name: LOG_LEVEL
            value: info
          - name: WIZ_ENV
            value: 
          - name: CLI_FILES_AS_ARGS
            value: "/var/api-client/clientToken,/var/api-client/clientId"
          - name: TARGET_IP
            value: kubernetes.default.svc.cluster.local
          - name: TARGET_PORT
            value: "443"
          - name: K8S_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: K8S_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: K8S_DEPLOYMENT_NAME
            value: wiz-connector-agent
          - name: WIZ_CHART_VERSION
            value: "3.0.3"
          - name: WIZ_IMAGE_REF
            value: "container-registry.zalando.net/secops-systems/wiz-broker:3.0.3-main-8"
          - name: WIZ_USE_HATUNNEL # toggle WebSocket usage on
            value: "1"
          - name: WIZ_BROKER_HEARTBEAT_DISABLE_CLUSTER_ID
            value: "1"
          - name: WIZ_AUTO_ROLLOUT_ROLE
            value: "false"
          - name: WIZ_HEALTH_PORT
            value: "30000"
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
            httpGet:
              port: 30000
              path: /ready
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 90 # 15 minutes
            httpGet:
              port: 30000
              path: /live
          ports:
            - containerPort: 30000
              name: health
          resources:
            limits:
              cpu: {{ .Cluster.ConfigItems.wiz_connector_cpu }} 
              memory: {{ .Cluster.ConfigItems.wiz_connector_memory }} 
            requests:
              cpu: {{ .Cluster.ConfigItems.wiz_connector_cpu }}
              memory: {{ .Cluster.ConfigItems.wiz_connector_memory }} 
{{end}}
