# {{ if eq .Cluster.ConfigItems.kube_node_decommissioner_enabled "true" }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: kube-node-decommissioner
  namespace: "kube-system"
  labels:
    application: kubernetes
    component: kube-node-decommissioner
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 300
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      activeDeadlineSeconds: 300
      backoffLimit: 0
      template:
        metadata:
          labels:
            application: kubernetes
            component: kube-node-decommissioner
          annotations:
            logging/destination: "{{.Cluster.ConfigItems.log_destination_infra}}"
        spec:
          serviceAccountName: kube-node-decommissioner
          restartPolicy: Never
          containers:
          - name: kube-node-decommissioner
            image: container-registry.zalando.net/teapot/kube-node-decommissioner:main-2
            resources:
              limits:
                cpu: 100m
                memory: 100Mi
              requests:
                cpu: 100m
                memory: 100Mi
# {{ end }}
