apiVersion: v1
kind: Service
metadata:
  name: vpa-updater
  namespace: kube-system
  labels:
    application: kubernetes
    component: vpa-updater
spec:
  ports:
    - port: 8943
      targetPort: 8943
      protocol: TCP
  selector:
    application: kubernetes
    component: vpa-updater
  type: ClusterIP
