apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpa-updater
  namespace: kube-system
  labels:
    application: kubernetes
    component: vpa-updater
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: vpa-updater
  template:
    metadata:
      labels:
        deployment: vpa-updater
        application: kubernetes
        component: vpa-updater
      annotations:
        logging/destination: "{{.Cluster.ConfigItems.log_destination_infra}}"
        prometheus.io/port: "8943"
        prometheus.io/path: "/metrics"
        prometheus.io/scheme: "http"
        prometheus.io/scrape: "true"
    spec:
      serviceAccountName: vpa-updater
      containers:
      - name: updater
        {{if eq .Cluster.ConfigItems.vertical_pod_autoscaler_version "new"}}
        image: container-registry.zalando.net/teapot/vpa-updater:v1.6.0-main-13-custom
        {{else if eq .Cluster.ConfigItems.vertical_pod_autoscaler_version "stable"}}
        image: container-registry.zalando.net/teapot/vpa-updater:v1.6.0-main-12-custom
        {{end}}
        command:
          - ./updater
        args:
          - --v=1
          - --logtostderr
          - --min-replicas=1
          - --evict-after-oom-threshold=12h
        resources:
          limits:
            cpu: {{.Cluster.ConfigItems.vpa_cpu}}
            memory: {{.Cluster.ConfigItems.vpa_mem}}
          requests:
            cpu: {{.Cluster.ConfigItems.vpa_cpu}}
            memory: {{.Cluster.ConfigItems.vpa_mem}}
        ports:
        - containerPort: 8943
          protocol: TCP
