apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    application: skipper-ingress
    component: ingress
  name: skipper-ingress
  namespace: kube-system
spec:
  maxUnavailable: 1%
  selector:
    matchLabels:
      application: skipper-ingress
      component: ingress
