# {{ if eq .Cluster.ConfigItems.skipper_eks_migration_svc_enabled "true" }}
apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: skipper-ingress-eks.{{ .Values.hosted_zone }}
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: application=skipper-ingress,component=ingress
    service.beta.kubernetes.io/aws-load-balancer-attributes: dns_record.client_routing_policy=availability_zone_affinity,load_balancing.cross_zone.enabled=false
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: /kube-system/healthz
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-scheme: internal
    service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: preserve_client_ip.enabled=true
  labels:
    application: skipper-ingress
    component: ingress
  name: skipper-internal-eks
  namespace: kube-system
spec:
  trafficDistribution: PreferSameZone
  externalTrafficPolicy: Local
  ports:
  - name: main
    port: 80
    protocol: TCP
    targetPort: 9999
  selector:
    application: skipper-ingress
    component: ingress
  type: LoadBalancer
  loadBalancerSourceRanges:
  - "{{ .Values.vpc_ipv4_cidr }}"
# {{ end }}
