# {{ $image := "container-registry.zalando.net/library/valkey-9-alpine:9-alpine3.22-20260316" }}
# {{ $version := index (split $image ":") 1 }}
{{- if eq .Cluster.ConfigItems.skipper_ingress_swarm_type "valkey" }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    application: skipper-ingress
    component: valkey
    version: "{{ $version }}"
  annotations:
    zalando.org/update-using-hpa-replicas: skipper-ingress-valkey
  name: skipper-ingress-valkey
  namespace: kube-system
spec:
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      statefulset: skipper-ingress-valkey
  serviceName: skipper-ingress-valkey
  template:
    metadata:
      labels:
        statefulset: skipper-ingress-valkey
        application: skipper-ingress
        component: valkey
        version: "{{ $version }}"
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
        karpenter.sh/do-not-disrupt: "true"
        logging/destination: "{{ .Cluster.ConfigItems.log_destination_both }}"
{{- if eq .Cluster.ConfigItems.skipper_topology_spread_enabled "true" }}
        zalando.org/topology-spread-timeout: 7m
{{- end }}
    spec:
{{- if eq .Cluster.ConfigItems.skipper_topology_spread_enabled "true" }}
      topologySpreadConstraints:
        - maxSkew: 1
          minDomains: 3
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              statefulset: skipper-ingress-valkey
{{- end }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchExpressions:
              - key: application
                operator: In
                values:
                - skipper-ingress
              - key: component
                operator: In
                values:
                - valkey
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: node.kubernetes.io/instance-type
                operator: In
                values:
                - c7i.large
                - m7i.large
          - weight: 50
            preference:
              matchExpressions:
              - key: node.kubernetes.io/instance-type
                operator: In
                values:
                - c6i.large
                - m6i.large
      priorityClassName: "{{ .Cluster.ConfigItems.system_priority_class }}"
      terminationGracePeriodSeconds: 45
      containers:
      - image: "{{ $image }}"
        name: skipper-ingress-valkey
        args:
        - valkey-server
        - --save
        - ""
        ports:
        - containerPort: 6379
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - valkey-cli
            - ping
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: {{ .Cluster.ConfigItems.skipper_valkey_cpu }}
            memory: {{ .Cluster.ConfigItems.skipper_valkey_memory }}
        lifecycle:
          preStop:
            sleep:
              seconds: 30
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
{{ if eq .Cluster.ConfigItems.enable_dedicate_nodepool_skipper_redis "true"}}
      nodeSelector:
        zalando.org/dedicated: skipper-ingress-redis
      tolerations:
      - key: "zalando.org/dedicated"
        operator: Exists
        effect: NoSchedule
{{ end }}
{{- end }}
