{{- if eq .Cluster.ConfigItems.parca_agent_enabled "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: parca-agent
  namespace: kube-system
  labels:
    application: kubernetes
    component: parca-agent
stringData:
  token: "{{ .Cluster.ConfigItems.parca_agent_token }}"
{{- end }}
