{{ if eq .Cluster.ConfigItems.flink_operator_enabled "true" }}
---
# Source: flink-kubernetes-operator/templates/flink-operator.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-kubernetes-operator
  namespace: kube-system
  labels:
    application: kubernetes
    component: flink-operator
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      application: kubernetes
      component: flink-operator
      app.kubernetes.io/name: flink-kubernetes-operator
  template:
    metadata:
      labels:
        application: kubernetes
        component: flink-operator
        app.kubernetes.io/name: flink-kubernetes-operator
      annotations:
        kubectl.kubernetes.io/default-container: flink-kubernetes-operator
    spec:
      securityContext:
        runAsGroup: 9999
        runAsUser: 9999
      serviceAccountName: flink-operator
      containers:
        - name: flink-kubernetes-operator
          image: "registry.opensource.zalan.do/library/flink-kubernetes-operator-1.10"
          imagePullPolicy: IfNotPresent
          command: ["/docker-entrypoint.sh", "operator"]
          ports:
            - containerPort: 8085
              name: health-port
              protocol: TCP
            - containerPort: 9999
              name: metrics-port
              protocol: TCP
          env:
            - name: OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: flink-kubernetes-operator
            - name: FLINK_CONF_DIR
              value: /opt/flink/conf
            - name: FLINK_PLUGINS_DIR
              value: /opt/flink/plugins
            - name: LOG_CONFIG
              value: -Dlog4j.configurationFile=/opt/flink/conf/log4j-operator.properties
            - name: JVM_ARGS
              value:
          resources:
            limits:
              cpu: {{ .Cluster.ConfigItems.flink_operator_cpu }}
              memory: {{ .Cluster.ConfigItems.flink_operator_memory }}
            requests:
              cpu: { { .Cluster.ConfigItems.flink_operator_cpu } }
              memory: { { .Cluster.ConfigItems.flink_operator_memory } }
          securityContext:
            {}
          volumeMounts:
            - name: flink-operator-config-volume
              mountPath: /opt/flink/conf
            - name: flink-artifacts-volume
              mountPath: /opt/flink/artifacts
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 10
            httpGet:
              path: /
              port: health-port
          startupProbe:
            failureThreshold: 30
            periodSeconds: 10
            httpGet:
              path: /
              port: health-port
      volumes:
        - name: flink-operator-config-volume
          configMap:
            name: flink-operator-config
            items:
              - key: flink-conf.yaml
                path: flink-conf.yaml
              - key: log4j-operator.properties
                path: log4j-operator.properties
              - key: log4j-console.properties
                path: log4j-console.properties
        - name: flink-artifacts-volume
          emptyDir: {}
{{ end }}

