{{ if eq .Cluster.ConfigItems.flink_operator_enabled "true" }}
---
# Source: flink-kubernetes-operator/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flink-operator
  labels:
    application: kubernetes
    component: flink-operator
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - configmaps
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
      - deletecollection
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - get
      - watch
      - list
      - create
      - update
      - patch
  - apiGroups:
      - apps
    resources:
      - deployments
      - deployments/scale
      - replicasets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - extensions
    resources:
      - deployments
      - ingresses
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - flink.apache.org
    resources:
      - flinkdeployments
      - flinksessionjobs
      - flinkstatesnapshots
      - flinkstatesnapshots/status
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - flink.apache.org
    resources:
      - flinkdeployments/status
      - flinksessionjobs/status
    verbs:
      - get
      - update
      - patch
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
---
# Source: flink-kubernetes-operator/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flink-operator-role-binding
  labels:
    application: kubernetes
    component: flink-operator
roleRef:
  kind: ClusterRole
  name: flink-operator
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: flink-operator
    namespace: kube-system
---
# Source: flink-kubernetes-operator/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flink
  namespace: kube-system
  labels:
    application: kubernetes
    component: flink-operator
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
# Source: flink-kubernetes-operator/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flink-role-binding
  namespace: kube-system
  labels:
    application: kubernetes
    component: flink-operator
roleRef:
  kind: Role
  name: flink
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: flink
    namespace: kube-system
{{ end }}
