---
# Source: flink-kubernetes-operator/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flink-operator
  namespace: kube-system
  labels:
    application: kubernetes
    component: flink-operator
    app.kubernetes.io/name: flink-kubernetes-operator
    app.kubernetes.io/version: "1.10.0"
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: flink-kubernetes-operator-1.10.0
---
# Source: flink-kubernetes-operator/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flink
  namespace: kube-system
  labels:
    application: kubernetes
    component: flink-operator
    app.kubernetes.io/name: flink-kubernetes-operator
    app.kubernetes.io/version: "1.10.0"
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: flink-kubernetes-operator-1.10.0
  annotations:
    helm.sh/resource-policy: keep