apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: eventtypesubscriptions.nakadi.zalan.do
spec:
  scope: Namespaced
  group: nakadi.zalan.do
  versions:
    - name: v1alpha1
      served: false
      storage: false
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                owningApplication:
                  type: string
                  description: Application owns subscription
                consumerGroup:
                  type: string
                eventTypes:
                  description: Event types to subscribe
                  type: array
                  items:
                    type: string
                readFrom:
                  type: string
                  enum: ["begin", "end", "cursors"]
                initialCursors:
                  type: array
                  items:
                    type: object
                    properties:
                      partition:
                        type: string
                      offset:
                        type: string
                      eventType:
                        type: string
                    required:
                      - partition
                      - offset
                      - eventType
                authorization:
                  type: object
                  description: |
                    The nakadi operator will always add itself as an admin.
                  properties:
                    admins:
                      type: array
                      items:
                        type: object
                        properties:
                          dataType:
                            type: string
                          value:
                            type: string
                        required:
                          - dataType
                          - value
                    readers:
                      type: array
                      items:
                        type: object
                        properties:
                          dataType:
                            type: string
                          value:
                            type: string
                        required:
                          - dataType
                          - value
                      minItems: 1
                  required:
                    - readers
              required:
                - owningApplication
                - eventTypes
                - authorization
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                createdAt:
                  type: string
                  description: Creation time of the subscription
                updatedAt:
                  type: string
                  description: Update time of the subscription
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: subscriptionId
          type: string
          description: Subscription Id
          jsonPath: .status.subscriptionId
        - name: owningApplication
          type: string
          description: Owning Application
          jsonPath: .spec.owningApplication
        - name: Age
          type: date
          description: The age of subscription
          jsonPath: .status.createdAt
        - name: Status
          type: string
          description: The status of subscription
          jsonPath: .status.status
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                owningApplication:
                  type: string
                  description: Application owns subscription
                consumerGroup:
                  type: string
                eventTypes:
                  description: Event types to subscribe
                  type: array
                  items:
                    type: string
                readFrom:
                  type: string
                  enum: ["begin", "end", "cursors"]
                initialCursors:
                  type: array
                  items:
                    type: object
                    properties:
                      partition:
                        type: string
                      offset:
                        type: string
                      eventType:
                        type: string
                    required:
                      - partition
                      - offset
                      - eventType
                authorization:
                  type: object
                  properties:
                    admins:
                      type: array
                      items:
                        type: object
                        properties:
                          dataType:
                            type: string
                          value:
                            type: string
                    readers:
                      type: array
                      items:
                        type: object
                        properties:
                          dataType:
                            type: string
                          value:
                            type: string
                  required:
                    - readers
              required:
                - owningApplication
                - eventTypes
                - authorization
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                createdAt:
                  type: string
                  description: Creation time of the subscription
                updatedAt:
                  type: string
                  description: Update time of the subscription
                error:
                  type: string
                  description: Contains the error message if status is ERROR.

      subresources:
        status: {}
      additionalPrinterColumns:
        - name: subscriptionId
          type: string
          description: Subscription Id
          jsonPath: .status.subscriptionId
        - name: owningApplication
          type: string
          description: Owning Application
          jsonPath: .spec.owningApplication
        - name: Age
          type: date
          description: The age of subscription
          jsonPath: .status.createdAt
        - name: Status
          type: string
          description: The status of subscription
          jsonPath: .status.status
        - name: Error Message
          type: string
          jsonPath: .status.error
          description: Shows error message.

  names:
    kind: EventTypeSubscription
    plural: eventtypesubscriptions
    singular: eventtypesubscription
    shortNames:
      - ets
