apiVersion: "zalando.org/v1"
kind: PlatformCredentialsSet
metadata:
  name: "nakadi-k8s-operator-credentials"
  namespace: "nakadi-k8s-operator"
spec:
  application: "nakadi-k8s-operator"
  token_version: v2
  tokens:
    nakadi:
      privileges:
        - com.zalando::nakadi.config.write
    nakadisql:
      privileges:
