apiVersion: v1
kind: ConfigMap
metadata:
  name: "nakadi-k8s-operator"
  namespace: "nakadi-k8s-operator"
data:
  APPLICATION_NAME: "nakadi-k8s-operator"
  NAKADI_URL: "{{ .Cluster.ConfigItems.nakadi_url }}"
  NSQL_URL: "{{ .Cluster.ConfigItems.nakadi_sql_url }}"
