{{ if eq .Cluster.ConfigItems.opa_admission_enabled "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: opa-admission-webhook-tls-certs
  namespace: kube-system
  labels:
    deployment: opa-admission-webhook
    application: kubernetes
    component: opa-admission-webhook
type: Opaque
data:
  opa-admission-webhook.pem: "{{ .Cluster.ConfigItems.opa_admission_webhook_cert }}"
  opa-admission-webhook-key.pem: "{{ .Cluster.ConfigItems.opa_admission_webhook_key }}"
{{ end }}
