# everything defined under here will be deleted before applying the manifests
# adding the StatefulSet temporary to migrate to Deployment with VPA
pre_apply:
- name: deployment-service-controller
  kind: StatefulSet
  namespace: kube-system
{{- if eq .Cluster.ConfigItems.skipper_redis_cleanup_enabled "true" }}
- kind: StatefulSet
  name: skipper-ingress-redis
- kind: HorizontalPodAutoscaler
  name: skipper-ingress-redis
- kind: Service
  name: skipper-ingress-redis
{{- end }}

# everything defined under here will be deleted after applying the manifests
post_apply:
# we deploy skipper-ingress-routesrv2 and need to delete the old
# routesrv deployment in order to change the spec.selector. In a
# second step we will rename it back to without 2, deleting the
# deployments with "2"
- name: skipper-ingress-routesrv
  namespace: kube-system
  kind: Deployment
# - name: skipper-ingress-routesrv2
#   namespace: kube-system
#   kind: Deployment
# - name: skipper-ingress-canary-routesrv2
#   namespace: kube-system
#   kind: Deployment
{{- if eq .Cluster.Provider "zalando-eks"}}
- name: coredns
  kind: Deployment
  namespace: kube-system
- name: coredns
  kind: ConfigMap
  namespace: kube-system
{{- if ne .Cluster.ConfigItems.eks_fis_support_enabled "true" }}
- name: fis-experiment
  kind: ClusterRoleBinding
- name: fis-experiment
  kind: ClusterRole
{{- end }}
{{- if ne .Cluster.ConfigItems.eks_efs_csi_support_enabled "true" }}
- name: efs-sc
  kind: StorageClass
{{- end }}
{{- end }}
{{ if eq .Cluster.ConfigItems.teapot_admission_controller_process_resources "true" }}
- name: limits
  namespace: default
  kind: LimitRange
- name: limits
  namespace: cron
  kind: LimitRange
{{ end }}
{{ if ne .Cluster.ConfigItems.fabric_gateway_custom_validation_enabled "true" }}
- name: "fabricgateway-policy.zalando.org"
  kind: ValidatingAdmissionPolicy
- name: "fabricgateway-policy.zalando.org"
  kind: ValidatingAdmissionPolicyBinding
{{ end }}
{{ if ne .Cluster.ConfigItems.polarsignals_enabled "true" }}
- name: polarsignals
  namespace: polarsignals
  kind: Secret
- name: polarsignals-agent
  namespace: polarsignals
  kind: DaemonSet
- name: polarsignals-agent
  namespace: polarsignals
  kind: ServiceAccount
- name: polarsignals-agent
  kind: ClusterRole
- name: polarsignals-agent
  kind: ClusterRoleBinding
- name: polarsignals
  kind: Namespace
{{ end }}
{{ if ne .Cluster.ConfigItems.downscaler_enabled "true" }}
- name: kube-downscaler
  namespace: kube-system
  kind: Deployment
- name: kube-downscaler
  namespace: kube-system
  kind: ServiceAccount
- name: kube-downscaler
  kind: ClusterRole
- name: kube-downscaler
  kind: ClusterRoleBinding
- name: kube-downscaler
  namespace: kube-system
  kind: VerticalPodAutoscaler
{{ end }}

{{ if ne .Cluster.ConfigItems.skipper_ingress_canary_enabled "true" }}
- name: skipper-ingress-canary
  namespace: kube-system
  kind: Deployment
{{ end }}

{{- if ne .Cluster.ConfigItems.skipper_oauth2_ui_login "true" }}
- kind: CronJob
  name: hostname-credentials-controller
  namespace: kube-system
- kind: ClusterRoleBinding
  name: hostname-credentials-controller
- kind: ClusterRole
  name: hostname-credentials-controller
- kind: ServiceAccount
  name: hostname-credentials-controller
  namespace: kube-system
- kind: PlatformCredentialsSet
  namespace: kube-system
  labels:
    application: skipper-ingress
    component: hostname-credentials
- kind: Secret
  name: hostname-credentials
  namespace: kube-system
{{- end }}

{{- if eq .Cluster.ConfigItems.prometheus_remote_write "disabled" }}
- name: prometheus-credentials
  kind: PlatformCredentialsSet
  namespace: kube-system
{{- end }}
{{ if eq .Cluster.ConfigItems.skipper_open_policy_agent_enabled "false" }}
- kind: ConfigMap
  name: open-policy-agent-config
  namespace: kube-system
- kind: ConfigMap
  name: webhook-open-policy-agent-config
  namespace: kube-system
{{ end }}
{{ if eq .Cluster.ConfigItems.hyped_article_lifecycle_management "false" }}
- name: hyped-articles-lifecycle-management
  kind: ClusterRole
- name: hyped-articles-lifecycle-management
  kind: ClusterRoleBinding
{{ end }}
{{ if eq .Cluster.ConfigItems.business_partner_service "false" }}
- name: business-partner-service
  kind: ClusterRole
- name: business-partner-service
  kind: ClusterRoleBinding
{{ end }}
{{ if eq .Cluster.ConfigItems.config_provider_service "false" }}
- name: config-provider-service
  kind: ClusterRole
- name: config-provider-service
  kind: ClusterRoleBinding
{{ end }}
{{ if ne .Cluster.ConfigItems.kubelet_summary_metrics_enabled "true" }}
- name: kubelet-summary-metrics
  kind: ClusterRole
- name: kubelet-summary-metrics
  kind: ClusterRoleBinding
- name: kubelet-summary-metrics
  kind: ServiceAccount
  namespace: kube-system
- name: kubelet-summary-metrics
  kind: Service
  namespace: kube-system
- name: kubelet-summary-metrics
  kind: Deployment
  namespace: kube-system
- name: kubelet-summary-metrics
  kind: HorizontalPodAutoscaler
  namespace: kube-system
{{ end }}
{{- if eq .Cluster.ConfigItems.audittrail_nakadi_url "" }}
- name: audittrail-adapter-nakadi
  kind: PlatformCredentialsSet
  namespace: kube-system
{{- end }}
{{- if ne .Cluster.ConfigItems.aws_cloud_controller_manager_enabled "true" }}
- name: aws-cloud-controller-manager
  kind: DaemonSet
  namespace: kube-system
- name: cloud-controller-manager
  kind: ServiceAccount
  namespace: kube-system
- name: system:cloud-controller-manager
  kind: ClusterRole
- name: cloud-controller-manager:apiserver-authentication-reader
  namespace: kube-system
  kind: RoleBinding
- name: system:cloud-controller-manager
  kind: ClusterRoleBinding
{{- end }}
- name: skipper-ingress
  kind: ClusterRole
  namespace: kube-system
- name: skipper-ingress
  kind: ClusterRoleBinding
  namespace: kube-system

- name: prometheus
  kind: Ingress
  namespace: kube-system

- name: deployment-service-status-service
  kind: Ingress
  namespace: kube-system

- name: skipper-canary-conrtroller
  kind: CronJob
  namespace: kube-system
{{- if ne .Cluster.ConfigItems.role_sync_controller_enabled "true" }}
- name: role-sync-controller
  kind: CronJob
  namespace: kube-system
- name: role-sync-controller
  kind: ClusterRole
- name: role-sync-controller
  kind: ClusterRoleBinding
- name: role-sync-controller
  kind: ServiceAccount
  namespace: kube-system
# secret-read role/bindings
- name: cdp-deployer-poweruser-secret-read
  kind: ClusterRoleBinding
- name: deployment-service-executor-poweruser-secret-read
  kind: ClusterRoleBinding
{{- end }}
{{- if ne .Cluster.ConfigItems.kube_janitor_enabled "true" }}
- name: kube-janitor
  kind: Deployment
  namespace: kube-system
- name: kube-janitor
  kind: ConfigMap
  namespace: kube-system
- name: kube-janitor
  kind: VerticalPodAutoscaler
  namespace: kube-system
- name: kube-janitor
  kind: ServiceAccount
  namespace: kube-system
- name: kube-janitor
  kind: ClusterRole
- name: kube-janitor
  kind: ClusterRoleBinding
{{- end }}
{{- if ne .Cluster.ConfigItems.wiz_enable_runtime_connector "true" }}
- name: wiz-kubernetes-connector-create-connector
  kind : Job
  namespace: wiz
- name: wiz-kubernetes-connector-delete-connector
  kind : Job
  namespace: wiz
- name: wiz-auto-modify-connector
  kind : ServiceAccount
  namespace: wiz
- name: wiz-auto-modify-connector
  kind : Role
  namespace: wiz
- name: wiz-auto-modify-connector
  kind : RoleBinding
  namespace: wiz
{{- end }}
{{- if ne .Cluster.ConfigItems.wiz_enable_runtime_connector_broker "true" }}
- name: wiz-connector-agent
  kind : Deployment
  namespace: wiz
{{- end }}
{{ if ne .Cluster.ConfigItems.sandbox_controller_enabled "true" }}
- name: sandbox-controller
  namespace: kube-system
  kind: Deployment
{{ end }}
{{ if ne .Cluster.ConfigItems.shadow_traffic_controller_enabled "true" }}
- name: shadow-traffic-controller
  namespace: kube-system
  kind: Deployment
- name: shadow-traffic-controller
  kind: ServiceAccount
  namespace: kube-system
- name: shadow-traffic-controller
  kind : ClusterRole
- name: shadow-traffic-controller
  kind : ClusterRoleBinding
{{ end }}
{{- if and (ne .Cluster.ConfigItems.wiz_enable_runtime_connector_broker "true") (ne .Cluster.ConfigItems.wiz_enable_runtime_connector "true") }}
- name: wiz-connector-connector
  kind : Secret
  namespace: wiz
- name: wiz-cluster-reader-token
  kind : Secret
  namespace: wiz
- name: wiz-api-token
  kind : Secret
  namespace: wiz
- name: wiz-cluster-reader
  kind : ServiceAccount
  namespace: wiz
- name: wiz-cluster-reader
  kind : ClusterRoleBinding
  namespace: wiz
- name: wiz-broker
  kind : ServiceAccount
  namespace: wiz
{{- end }}
{{- if ne .Cluster.ConfigItems.wiz_enable_runtime_sensor "true" }}
- name: wiz-sensor
  kind : DaemonSet
  namespace: wiz
- name: wiz-sensor
  kind: ServiceAccount
  namespace: wiz
- name: wiz-sensor-api-token
  kind: Secret
  namespace: wiz
- name: wiz-sensor
  kind : ClusterRole
  namespace: wiz
- name: wiz-sensor
  kind : ClusterRoleBinding
  namespace: wiz
{{- end }}
{{- if and (ne .Cluster.ConfigItems.wiz_enable_runtime_connector_broker "true") (ne .Cluster.ConfigItems.wiz_enable_runtime_sensor "true") }}
- name: wiz
  kind: Namespace
{{- end }}
{{- if ne .Cluster.ConfigItems.aws_efa_device_plugin_enabled "true"}}
- name: aws-efa-k8s-device-plugin
  kind: DaemonSet
  namespace: kube-system
- name: aws-efa-k8s-device-plugin
  kind: ServiceAccount
  namespace: kube-system
{{- end}}
{{- if ne .Cluster.ConfigItems.eks_node_monitoring_enabled "true"}}
- name: eks-node-monitoring-agent
  kind: DaemonSet
  namespace: kube-system
- name: eks-node-monitoring-agent
  kind: ServiceAccount
  namespace: kube-system
- name: eks-node-monitoring-agent
  kind: ClusterRole
- name: eks-node-monitoring-agent
  kind: ClusterRoleBinding
- name: eks-node-monitoring-agent-extended
  kind: ClusterRole
- name: eks-node-monitoring-agent-extended
  kind: ClusterRoleBinding
{{- end}}
{{- if ne .Cluster.ConfigItems.kube_node_decommissioner_enabled "true"}}
- name: kube-node-decommissioner
  kind: CronJob
  namespace: kube-system
- name: kube-node-decommissioner
  kind: ClusterRole
- name: kube-node-decommissioner
  kind: ClusterRoleBinding
- name: kube-node-decommissioner
  kind: ServiceAccount
  namespace: kube-system
{{- end}}
{{- if ne .Cluster.ConfigItems.scheduled_scaling_vpa_enabled "true"}}
- name: scheduled-scaling-vpa
  kind: CronJob
  namespace: kube-system
- name: scheduled-scaling-vpa
  kind: ClusterRole
- name: scheduled-scaling-vpa
  kind: ClusterRoleBinding
- name: scheduled-scaling-vpa
  kind: ServiceAccount
  namespace: kube-system
- name: verticalpodautoscalers.zalando.org
  kind: CustomResourceDefinition
{{- end}}
{{ if not (index .Cluster.ConfigItems "efs_id") }}
- name: efs-provisioner
  kind: VerticalPodAutoscaler
  namespace: kube-system
- name: efs-provisioner
  kind: Deployment
  namespace: kube-system
- name: efs-provisioner
  kind: ConfigMap
  namespace: kube-system
- name: efs-provisioner
  kind: ServiceAccount
  namespace: kube-system
- name: efs-provisioner-runner
  kind: ClusterRole
- name: leader-locking-efs-provisioner
  kind: Role
  namespace: kube-system
- name: leader-locking-efs-provisioner
  kind: RoleBinding
  namespace: kube-system
- name: efs-provisioner-privileged-psp
  kind: RoleBinding
  namespace: kube-system
- name: aws-efs
  kind: StorageClass
{{ end }}
{{- if ne .Cluster.ConfigItems.capability_kro_enabled "true"}}
- name: kro-poweruser
  kind: ClusterRoleBinding
- name: kro-poweruser-secret-read
  kind: ClusterRoleBinding
{{- end }}
