{{ if eq .Cluster.ConfigItems.wiz_enable_runtime_monitoring_daemonset "true"}}
---
# Source: wiz-sensor/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wiz-sensor
  labels:
    helm.sh/chart: wiz-sensor-1.0.4760
    image/tag: v1
    app.kubernetes.io/name: wiz-sensor
    app.kubernetes.io/instance: wiz-sensor
    app.kubernetes.io/version: "1.0.4708"
    app.kubernetes.io/managed-by: Helm
rules:
  - apiGroups: [""]
    resources: ["pods", "namespaces", "nodes", "replicationcontrollers", "serviceaccounts"]
    verbs: ["get", "list", "watch"]

  - apiGroups: ["apps"]
    resources: ["daemonsets", "replicasets", "deployments", "statefulsets"]
    verbs: ["get", "list", "watch"]

  - apiGroups: ["batch"]
    resources: ["cronjobs"]
    verbs: ["get", "list", "watch"]
---
# Source: wiz-sensor/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wiz-sensor
  labels:
    
    helm.sh/chart: wiz-sensor-1.0.4760
    image/tag: v1
    app.kubernetes.io/name: wiz-sensor
    app.kubernetes.io/instance: wiz-sensor
    app.kubernetes.io/version: "1.0.4708"
    app.kubernetes.io/managed-by: Helm
subjects:
- kind: ServiceAccount
  name: wiz-sensor
  namespace: wiz
roleRef:
  kind: ClusterRole
  name: wiz-sensor
  apiGroup: rbac.authorization.k8s.io
{{end}}}
