{{ if eq .Cluster.ConfigItems.wiz_enable_runtime_monitoring_daemonset "true"}}
---
# Source: wiz-sensor/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wiz-sensor
  namespace: wiz
  labels:
    
    helm.sh/chart: wiz-sensor-1.0.4760
    image/tag: v1
    app.kubernetes.io/name: wiz-sensor
    app.kubernetes.io/instance: wiz-sensor
    app.kubernetes.io/version: "1.0.4708"
    app.kubernetes.io/managed-by: Helm
{{end}}}
