apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "build-scaling-console"
  labels:
    application: "build-scaling-console"
    team: builder-infrastructure
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list"]
- apiGroups:
  - "zalando.org"
  resources:
  - stacksets
  - stacks
  verbs:
  - get
  - list
- apiGroups:
  - "apps"
  resources:
  - deployments
  - statefulsets
  verbs:
  - get
  - list
- apiGroups:
  - "batch"
  resources:
  - jobs
  - cronjobs
  verbs:
  - get
  - list
- apiGroups:
  - "autoscaling"
  resources:
  - horizontalpodautoscalers
  verbs:
  - get
  - list
- apiGroups:
  - "autoscaling.k8s.io"
  resources:
  - verticalpodautoscalers
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: build-scaling-console
  labels:
    application: "build-scaling-console"
    team: builder-infrastructure
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "build-scaling-console"
subjects:
- kind: User
  name: zalando-iam:zalando:service:stups_build-scaling-console
