apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubernetes-unit-costs
  labels:
    application: kubernetes-unit-costs
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubernetes-unit-costs
  labels:
    application: kubernetes-unit-costs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubernetes-unit-costs
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: zalando-iam:zalando:service:stups_kubernetes-unit-costs
